name: "Chromatic"

on:
  push:
    paths:
      - "webui/musicplayer/**"
      - ".github/workflows/chromatic.yml"
  workflow_dispatch:

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.37
      - name: Setup Fluent CI CLI
        run: deno install -A -r https://cli.fluentci.io -n fluentci
      - name: Setup Dagger
        run: |
          curl -L https://dl.dagger.io/dagger/install.sh | DAGGER_VERSION=0.8.8 sh
          sudo mv bin/dagger /usr/local/bin
          dagger version
      - uses: actions/checkout@v1
      - name: Publish to Chromatic
        run: |
          cp -r ../../.git .
          fluentci run chromatic_pipeline publish
        working-directory: ./webui/musicplayer
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
