name: "Chromatic"

on:
  push:
    paths:
      - "webui/musicplayer/**"
      - ".github/workflows/chromatic.yml"
  workflow_dispatch:

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - name: Setup Fluent CI
        uses: fluentci-io/setup-fluentci@v1
      - uses: actions/checkout@v1
      - name: Publish to Chromatic
        run: |
          cp -r ../../.git .
          fluentci run chromatic_pipeline publish
        working-directory: ./webui/musicplayer
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
