name: tests

on:
  push:
    branches: ["master"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ["master"]
  workflow_dispatch:

jobs:
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          remove-dotnet: "true"
          remove-android: "true"
          remove-haskell: "true"
          remove-docker-images: "true"
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.37
      - name: Setup Fluent CI CLI
        run: deno install -A -r https://cli.fluentci.io -n fluentci
      - name: Setup Dagger
        run: |
          curl -L https://dl.dagger.io/dagger/install.sh | DAGGER_VERSION=0.8.8 sh
          sudo mv bin/dagger /usr/local/bin
          dagger version
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Dagger Pipelines
        run: fluentci run . test
      - name: Upload to Codecov
        run: fluentci run codecov_pipeline
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
