name: tests

on:
  push:
    branches: ["master"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ["master"]
  workflow_dispatch:

jobs:
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup Fluent CI
        uses: fluentci-io/setup-fluentci@v1
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Dagger Pipelines
        run: fluentci run . test
      - name: Upload to Codecov
        run: fluentci run codecov_pipeline
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
